# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7s15ftgb196-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Users/onuong/LowFilter/LowFilter.cache/wt [current_project]
set_property parent.project_path D:/Users/onuong/LowFilter/LowFilter.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  d:/Users/onuong/FPGA_IP/ADC-IP/IP
  d:/Users/onuong/FPGA_IP/DAC-IP/IP
  d:/Users/onuong/FPGA_IP/Frequency-Divider-IP/IP
} [current_project]
update_ip_catalog
set_property ip_output_repo d:/Users/onuong/LowFilter/LowFilter.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/Users/onuong/LowFilter/Sin_Wave_Rom.coe
read_verilog -library xil_defaultlib {
  D:/Users/onuong/LowFilter/LowFilter.srcs/sources_1/new/ADC_Driver.v
  D:/Users/onuong/LowFilter/LowFilter.srcs/sources_1/new/DAC_Driver.v
  D:/Users/onuong/LowFilter/LowFilter.srcs/sources_1/new/Fir.v
  D:/Users/onuong/LowFilter/LowFilter.srcs/sources_1/new/LowFilter.v
}
read_ip -quiet D:/Users/onuong/LowFilter/LowFilter.srcs/sources_1/ip/Wave_Ram/Wave_Ram.xci
set_property used_in_implementation false [get_files -all d:/Users/onuong/LowFilter/LowFilter.srcs/sources_1/ip/Wave_Ram/Wave_Ram_ooc.xdc]

read_ip -quiet D:/Users/onuong/LowFilter/LowFilter.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci
set_property used_in_implementation false [get_files -all d:/Users/onuong/LowFilter/LowFilter.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/Users/onuong/LowFilter/LowFilter.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc]
set_property used_in_implementation false [get_files -all d:/Users/onuong/LowFilter/LowFilter.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc]

read_ip -quiet D:/Users/onuong/LowFilter/LowFilter.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/Users/onuong/LowFilter/LowFilter.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Users/onuong/LowFilter/LowFilter.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/Users/onuong/LowFilter/LowFilter.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top LowFilter -part xc7s15ftgb196-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef LowFilter.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file LowFilter_utilization_synth.rpt -pb LowFilter_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
