# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Users/onuong/LowFilter/LowFilter.srcs/sources_1/ip/Wave_in/Wave_in.xci
# IP: The module: 'Wave_in' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/onuong/LowFilter/LowFilter.srcs/sources_1/ip/Wave_in/Wave_in_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Wave_in'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Users/onuong/LowFilter/LowFilter.srcs/sources_1/ip/Wave_in/Wave_in.xci
# IP: The module: 'Wave_in' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/onuong/LowFilter/LowFilter.srcs/sources_1/ip/Wave_in/Wave_in_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Wave_in'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
